
spring:
  profiles:
    active: home
  activiti:
    check-process-definitions: false
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

password:
  default: 123456
  algorithm: MD5
  count: 5
lm:
  key: 1993

server:
  port: 80

#控制台打印sql
logging:
  level:
    com:
      curou:
        oa:
          dao: debug

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

---

spring:
  profiles: dev
  datasource:
    username: root
    password: Root!!2019
    url: jdbc:mysql://202.60.236.141:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


---


spring:
  profiles: home
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/laoma?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver










